package gonfigurator

// AUTOGENERATED BY MOQ
// github.com/matryer/moq

// ConfigLoaderMock is a mock implementation of ConfigLoader.
//
//     func TestSomethingThatUsesConfigLoader(t *testing.T) {
//
//         // make and configure a mocked ConfigLoader
//         mockedConfigLoader := &ConfigLoaderMock{ 
//             ParseFunc: func(path string, target interface{}) error {
// 	               panic("TODO: mock out the Parse function")
//             },
//             PathFunc: func() string {
// 	               panic("TODO: mock out the Path function")
//             },
//         }
//
//         // TODO: use mockedConfigLoader in code that requires ConfigLoader
//     
//     }
type ConfigLoaderMock struct {
	// ParseFunc mocks the Parse function.
	ParseFunc func(path string, target interface{}) error
	// PathFunc mocks the Path function.
	PathFunc func() string
}

// Parse calls ParseFunc.
func (mock *ConfigLoaderMock) Parse(path string, target interface{}) error {
	if mock.ParseFunc == nil {
		panic("moq: ConfigLoaderMock.ParseFunc is nil but was just called")
	}
	return mock.ParseFunc(path, target)
}

// Path calls PathFunc.
func (mock *ConfigLoaderMock) Path() string {
	if mock.PathFunc == nil {
		panic("moq: ConfigLoaderMock.PathFunc is nil but was just called")
	}
	return mock.PathFunc()
}
