package gonfigurator

// AUTOGENERATED BY MOQ
// github.com/matryer/moq

// LoaderBlueprintMock is a mock implementation of LoaderBlueprint.
//
//     func TestSomethingThatUsesLoaderBlueprint(t *testing.T) {
//
//         // make and configure a mocked LoaderBlueprint
//         mockedLoaderBlueprint := &LoaderBlueprintMock{ 
//             ParseFunc: func(in1 string, in2 interface{}) error {
// 	               panic("TODO: mock out the Parse function")
//             },
//         }
//
//         // TODO: use mockedLoaderBlueprint in code that requires LoaderBlueprint
//     
//     }
type LoaderBlueprintMock struct {
	// ParseFunc mocks the Parse function.
	ParseFunc func(in1 string, in2 interface{}) error
}

// Parse calls ParseFunc.
func (mock *LoaderBlueprintMock) Parse(in1 string, in2 interface{}) error {
	if mock.ParseFunc == nil {
		panic("moq: LoaderBlueprintMock.ParseFunc is nil but was just called")
	}
	return mock.ParseFunc(in1, in2)
}
